name: Go CI & Docker Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test Code
        run: go test -v ./...

      # ШАГ-ИСПРАВЛЕНИЕ: Переводим имя репозитория в lowercase силами самого Bash
      - name: Set lower case repo name
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Теперь безопасно используем переменную, которую создал Bash на предыдущем шаге
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

