name: Go CI & Docker Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test Code
        run: go test -v ./...

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Используем встроенную функцию ${{ format(...) }} и фукнцию string.lowercase для принудительного нижнего регистра
          tags: |
            ghcr.io/${{ text.toLower(github.repository) }}:latest
            ghcr.io/${{ text.toLower(github.repository) }}:${{ github.sha }}

